print("Hello world!")
print("Hello world!")
print("Hello world!")
print("Hello world!")
print("Hello world!")
print("\n")

print("온세상이 소넌석")
print("온세상이 소넌석")
print("온세상이 소넌석")
print("온세상이 소넌석")
print("온세상이 소넌석")
print("\n")

print("젠장 또 너야 소넌석?")
print("젠장 또 너야 소넌석?")
print("젠장 또 너야 소넌석?")
print("젠장 또 너야 소넌석?")
print("젠장 또 너야 소넌석?")
